### PR TITLE
Fix cache notification locking semantics [1571]

### PR DESCRIPTION
**Pull request by MarkZuber**
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1571

### CODE REVIEW

**Review by jennyf19 — APPROVED** [review]
LGTM

**Review by bgavrilMS — APPROVED** [review]
I don't see the whole code, but as long we don't double notify (i.e. notify during a notification), LGTM

**Review by bgavrilMS — APPROVED** [review]

**Comment by jmprieur** [comment]
which problem is it solving?

**Comment by bgavrilMS** [comment]
@jmprieur The current implementation is causing deadlocks if the token cache file is syncronized from the outside. Check out the bug https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1571 to see a deadlock.

**Pull request merged**
