### PR TITLE
Remove the ADAL platform dll

### PR DESCRIPTION
**Pull request by bgavrilMS**
This is not used in ADAL v4 and removing it is trivial (some minor changes will be required for the build)

### CODE REVIEW

**Review by jennyf19 — APPROVED** [review]
awesome. 🐈

**Comment by bgavrilMS** [comment]
Build will fail because I renamed the sln file ....

**Comment by henrik-me** [comment]
I'm ok with this change as right after we have shipped our current bits. Perhaps the the CoreAndUtests.sln file should also be renamed. NoSamples or LibsAndUtests?

**Review by henrik-me — APPROVED** [review]
:shipit:

**Comment by jmprieur** [comment]
why did you remove the branch @bgavrilMS ? it would be useful later?

**Pull request closed without merging**
