### PR TITLE
Enable rule UseAsyncSuffix and set it to error level + code fixes.

### PR DESCRIPTION
**Pull request by bgavrilMS**
Note that all the changes were done through refactoring, so there should be very low risk. As far as I can tell, the only public changes are in MSAL - GetUser, GetUsers and Remove

### CODE REVIEW

**Review by jennyf19 — APPROVED** [review]
🤖

**Comment by henrik-me** [comment]
>     class AcquireTokenByAuthorizationCodeHandler : AcquireTokenHandlerBase

would have been nice if this one (and a few other places) was marked as internal

---
Refers to: adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Flows/AcquireTokenByAuthorizationCodeHandler.cs:35 in 1965741. [](commit_id = 196574149e1f24f8c46bdad0e10e99c9202bfa06, deletion_comment = False)

**Comment by henrik-me** [comment]
Generally ok. Sample apps needs to be updated :)
As far as I could spot there are only the 2 public api changes to MSAL, right?

**Review by henrik-me — APPROVED** [review]
:shipit:

**Comment by bgavrilMS** [comment]
@henrik-me  - there are 3 public api changes in MSAL - GetUserAsync, GetUsersAsync and RemoveAsync

**Pull request merged**
