### PR TITLE
Fix binary compat with ADAL 2.x for calls to AuthenticationContext.AcquireTokenAsync

### PR DESCRIPTION
**Pull request by TimLovellSmith**
Because I believe if it is not necessary to break binary compat, it is just better not to! For discussion see #1085.

### CODE REVIEW

**Comment by henrik-me** [comment]
Thanks for pointing out the issues with binary compatibility.

"fixing" this will need more work. Also there are more breaking changes between v2 and v3 than this. 
At this point this change would break existing v3.
Aside: the current dev branch is for vNext of ADAL and MSAL. (Which may even break v3 and thus we may be able to accomodate this change)

**Comment by TimLovellSmith** [comment]
@henrik-me Hi Henrik, which one is the v3 branch? And how does this break v3?

**Comment by henrik-me** [comment]
adalv3dev is the current v3 branch. because the change is going into v3 (or later) then IMO this is as breaking as when the change went the other way between 2 and 3.

**Comment by TimLovellSmith** [comment]
@henrik-me What exactly is the breaking change that you think I'm making?

**Comment by henrik-me** [comment]
See discussion in #1085. Closing this PR. It's something we may consider for v4 as a general element of removing extension methods.

**Pull request closed without merging**
