### PR TITLE
Added tests for AuthenticationParameters.CreateFromUnauthorizedResponseAsync()

### PR DESCRIPTION
**Pull request by abatishchev**
Related to #1731 and #1732.

### CODE REVIEW

**Comment by abatishchev** [comment]
I wish I could figure out why none of the scripts don't work for me. Neither does the CI builds. Nor just opening VS and building/running tests.
So I cant verify this change beyond it does compile.

**Comment by jmprieur** [comment]
@abatishchev: to answer your question on the scripts, did you see the [pre-requisites](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Pre-requisites-to-build-ADAL.NET-and-MSAL.NET) ?

**Comment by jmprieur** [comment]
@abatishchev : ADAL is now in maintenance mode. We don't plan releasing a new version.

**Comment by abatishchev** [comment]
@jmprieur yes, I've read that. I don't have Android SDK or Xamarin indeed. However I'd expect VS2019 to be able to build the library itself or at least show meaningful errors.
The scripts in the root launch child scripts in separate windows, the blink, fail, I can't see what's the errors are.
I hope to ping @bgavrilMS during the work week, maybe he'll able to suggest how make it working.

**Comment by abatishchev** [comment]
@jmprieur do you know why the gated build doesn't run? Is it dead?

**Comment by jmprieur** [comment]
@trwalke @pmaytak ^^

**Comment by pmaytak** [comment]
@abatishchev About the CI builds - we don't run them on forked repos.
I'm not sure about how ADAL is set up, but in MSAL the workaround is to remove the unneeded target frameworks (like Xamarin) from the csproj file and it would build.

**Comment by abatishchev** [comment]
@pmaytak thanks! I've managed to build and run tests from VS. Fixed my changes, now all tests pass:

| netstandard1.3 | net45;
|--|--|
| image | image |

Feel free to complete the PR or not. I've made little-to-no functional changes to the library itself, other than additional parameter check which I can remove if needed.

I think it should be _fine_ to accept the change, so in case of an emergency release in the future - you'd have higher confidence in the changes made. /cc @jmprieur

**Comment by bgavrilMS** [comment]
@abatishchev - appreciate you trying to contribute, but ADAL is deprecated and we'd rather not touch it, unless there is a serious issue. Any changes to MSAL are highly appreciated and we'd prioritize them.

**Comment by bgavrilMS** [comment]
Not taking changes to ADAL

**Pull request closed without merging**
