### PR TITLE
Fix for silent broker flow on android

### PR DESCRIPTION
**Pull request by trwalke**
Fix for https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1687

### CODE REVIEW

**Comment by trwalke** [comment]
This fix has been E2E tested by the customer

**Comment by henrik-me** [comment]
What tests do we have for validating? Also has it been validated we don't have the same or a similar issue in MSAL?

---
In reply to: [573249367](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1688#issuecomment-573249367) [](ancestors = 573249367)

**Comment by jennyf19** [comment]
Agree with henrik...is there a way to do whatever the internal customer was doing to validate on our end as well and have a test for it?

---
In reply to: [573251223](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1688#issuecomment-573251223) [](ancestors = 573251223,573249367)

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Pull request merged**
