### PR TITLE
Adding Resource Owner Credentials flow support for ADFS w/ some test coverage

### PR DESCRIPTION
**Pull request by ptsurbeleu**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-106089252%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-111596296%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-112240032%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197%23issuecomment-106089252%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40ptsurbeleu__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3EYou%27ve%20already%20signed%20the%20contribution%20license%20agreement.%20Thanks%21%3C/span%3E%5Cr%5Cn%20%20%20%20%20%20%20%20%3Cp%3EThe%20agreement%20was%20validated%20by%20Microsoft%20Open%20Technologies%2C%20Inc.%20and%20real%20humans%20are%20currently%20evaluating%20your%20PR.%3C/p%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-27T21%3A53%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22code%20looks%20fine%20but%20it%20would%20be%20nice%20to%20have%20a%20comment%20in%20the%20public%20header%20to%20clarify%20that%20this%20only%20works%20with%20AAD%20and%20Windows%2010.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-06-12T19%3A37%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22Added%20a%20note%20into%20the%20public%20API%20header%20about%20the%20environments%20that%20support%20the%20suggested%20feature.%22%2C%20%22created_at%22%3A%20%222015-06-15T23%3A55%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3822219%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ptsurbeleu%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197#issuecomment-106089252'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@ptsurbeleu__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>You've already signed the contribution license agreement. Thanks!</span>
<p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>
TTYL, MSOTBOT;
- <a href='https://github.com/kpanwar'></a> code looks fine but it would be nice to have a comment in the public header to clarify that this only works with AAD and Windows 10.
- <a href='https://github.com/ptsurbeleu'></a> Added a note into the public API header about the environments that support the suggested feature.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/197'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by msotclas** [comment]
Hi __@ptsurbeleu__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by kpanwar** [comment]
code looks fine but it would be nice to have a comment in the public header to clarify that this only works with AAD and Windows 10.

**Comment by ptsurbeleu** [comment]
Added a note into the public API header about the environments that support the suggested feature.

**Pull request merged**
